project:
  type: website

format:
  html:
    fontsize:  "1.0em"
    theme:   
      dark: darkly
      light: cerulean
    css: styles.css
    toc: true
    toc-depth: 5
    email-obfuscation: javascript
    smooth-scroll: true
    #backgroundcolor: black
    code-link: true
    #code-block-bg: "#29465B"
    code-line-numbers: "true"
    code-overflow: "wrap" 

website:
  title: "vcalvache"
  navbar:
    right:
      - file: index.qmd
        text: Home
      - file: about.qmd
        text: About me
      - file: javase.qmd
        text: Java SE
      - file: labs.qmd
        text: Labs




