project:
  type: website

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true


website:
  title: "vcalvache"
  #cookie-consent: true
  
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "About me"
        file: about.qmd
      - text: "Java SE"
        file: javase.qmd
      - text: "Labs"
        file: labs.qmd

  sidebar:      
      - title: "Labs"
        style: "docked"
        contents:
          - lab_se02_1.qmd
          - lab_se02_2.qmd      





