project:
  type: website

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true


website:
  title: "vcalvache"
  #cookie-consent: true
  
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Java SE"
        file: javase.qmd
      - text: "Laboratories"
        file: laboratories/labs.qmd
      - text: "IFCD0210"
        file: ifcd0210/deliveries.qmd
      - text: "About me"
        file: about_me/about.qmd  

  sidebar:      
      - title: "Labs"
        style: "docked"
        contents:
          - java_labs/labse00_1.qmd
          - java_labs/labse00_2.qmd
          - java_labs/labse00_3.qmd
          - java_labs/labse00_4.qmd
          - java_labs/labse01_1.qmd
          - java_labs/labse01_2.qmd
          - java_labs/labse02_1.qmd
          - java_labs/labse02_2.qmd
          - java_labs/labse02_3.qmd
          - java_labs/labse02_4.qmd
          - java_labs/labse02_5.qmd
          - java_labs/labse03_1.qmd
          - java_labs/labse03_2.qmd
          - java_labs/labse03_3.qmd
  





