project:
  type: website

format:
  html:
    theme:
      light: spacelab
      dark: cyborg
    css: styles.css
    toc: true


website:
  title: "vcalvache"
  #cookie-consent: true
  
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Java SE"
        file: javase.qmd
      - text: "Laboratories"
        file: laboratories/labs.qmd
      - text: "IFCD0210"
        file: ifcd0210/deliveries.qmd
      - text: "About me"
        file: about_me/about.qmd  

  sidebar:    
      - id: javalabs
        title: "Java Laboratories"
        style: "docked"
        contents:
          - text: "Lab#SE00-01"
            file: laboratories/java_labs/labse00_1.qmd
          - text: "Lab#SE00-02"
            file: laboratories/java_labs/labse00_2.qmd
          - text: "Lab#SE00-03"
            file: laboratories/java_labs/labse00_3.qmd
          - text: "Lab#SE00-04"
            file: laboratories/java_labs/labse00_4.qmd
          - text: "Lab#SE01-01"
            file: laboratories/java_labs/labse01_1.qmd
          - text: "Lab#SE01-02"
            file: laboratories/java_labs/labse01_2.qmd
          - text: "Lab#SE02-01"
            file: laboratories/java_labs/labse02_1.qmd
          - text: "Lab#SE02-02"
            file: laboratories/java_labs/labse02_2.qmd
          - text: "Lab#SE02-03"
            file: laboratories/java_labs/labse02_3.qmd
          - text: "Lab#SE02-04"
            file: laboratories/java_labs/labse02_4.qmd
          - text: "Lab#SE02-05"
            file: laboratories/java_labs/labse02_5.qmd
          - text: "Lab#SE03-01"
            file: laboratories/java_labs/labse03_1.qmd
          - text: "Lab#SE03-02"
            file: laboratories/java_labs/labse03_2.qmd
          - text: "Lab#SE03-03"
            file: laboratories/java_labs/labse03_3.qmd
   
      - id: springlabs
        title: "Spring Boot Laboratories"
        style: "docked"
        contents:
          - text: "UF01-1844"
            file: laboratories/spring_boot_labs/UF01-1844.qmd
          - text: "UF02-1845"
            file: laboratories/spring_boot_labs/UF02-1845.qmd