---
title: "IFCD0210"
sidebar: false
---

Here you can read the subjects to be delivered and links to the specified tasks.

---

## Subjects

Here you can read the subjects to be delivered:

### Front-End

| Code | Date | Description|
|---|---|---|
| **MF01-0491**  | **12/12/2022**  | **Front-end** |
| UF01-1841 | 13/01/2023  | Prototip [WebApp Quarto](https://albertprofe.github.io/wiki/markup/markup-quarto-create.html): web multipage, markdwon/HTML, with github repository and gh-pages deployement |
| UF02-1842 | 10/02/2023  | WebApp Quarto amb [advanced features](https://albertprofe.github.io/wiki/markup/markup-quarto-basics.html): markdown basics, figures, tables, Mermaid Diagrams, callout, cross-references, code highlighted   |
| UF03-1843 | 20/02/2023  | WebApp Quarto amb [Document Listings](https://quarto.org/docs/websites/website-listings.html){.external} |
| MF01-0492 | 21/02/2023  | Prova objectiva i prova pràctica</br>  - WebApp Quarto amb [Api REST call to server and render the data from JSON](https://albertprofe.github.io/wiki/markup/markup-quarto-api-rest.html), from cloud-external server or Spring Boot local server </br>  - WebApp Quarto amb a [Observable JS script cell](https://albertprofe.github.io/wiki/markup/markup-quarto-code.html#observable-js) |


### Back-End

| Code | Date | Description|
|---|---|---|
| **MF02-0492**  | **21/02/2022**  | **Back-end** |
| UF01-1844 | 20/03/2023  | Laboratori app MVC amb Spring Boot Thyemeleaf (alternatiu Rest) un objecte amb totes les operacions CRUD |
| UF02-1845 | 19/04/2023  | Laboratori app Spring Boot Thyemeleaf (opcional Rest) amb H2 JPA (alternatiu objectes amb Composition/Inherence) |
| UF03-1846 | 09/05/2023  | Laboratori app web amb React Hooks |
| MF02-0492 | 10/05/2023  | Prova objectiva i prova pràctica (triar una opció)</br>  - Laboratori app Spring Boot amb React </br>  - Laboratori Spring Boot Server-Data API Rest amb Spring Boot Client-Web-Thymeleaf </br>  -  Laboratori app Spring Boot Thynmeleaf deployat a AWS </br> -  Laboratori app web amb React Hooks amb Data API Rest |

## Deliveries
---

### Front-End

| Code | Date | Delivery|
|---|---|---|
| **MF01-0491**  | **12/12/2022**  | **Front-end** |
| UF01-1841 | 13/01/2023  | - `Website:` [WebApp Quarto](https://vcalvache.github.io/mywebsite) </br> - `GitHub repo:` [Repo](https://github.com/vcalvache/mywebsite)|
| UF02-1842 | 10/02/2023  | WebApp Quarto with [advanced features](https://vcalvache.github.io/mywebsite/laboratories/advanced_features.html): markdown basics, figures, tables, Mermaid Diagrams, callout, cross-references, code highlighted   |
| UF03-1843 | 20/02/2023  | WebApp Quarto with [Document Listings](https://vcalvache.github.io/mywebsite/laboratories/labs.html)|
| MF01-0492 | 21/02/2023  |  - WebApp Quarto  with [Api REST call to server and render the data from JSON](https://vcalvache.github.io/mywebsite/laboratories/api_rest_call.html) </br>  - WebApp Quarto with [Observable JS script cell](https://vcalvache.github.io/mywebsite/laboratories/observable_js_cell.html) |

### Back-End

| Code | Date | Delivery|
|---|---|---|
| **MF02-0492**  | **21/02/2022**  | **Back-end** |
| UF01-1844 | 20/03/2023  | Student Manager MVC Spring [Spring MVC](../laboratories/spring_boot_labs/UF01-1844.qmd) |
| UF02-1845 | 19/04/2023  | Movie Review API Rest with MONGO DB [Spring API REST](../laboratories/spring_boot_labs/UF02-1845-mongo.qmd) |
|           |             | Mepple Match project [Meeple Match](../laboratories/spring_boot_labs/UF02-1845.qmd) | 
| UF03-1846 | 09/05/2023  | Simple react Lab with Hooks [React Hookc](../react/react-delivery.qmd) |
| MF02-0492 | 10/05/2023  |  |
