---
title: "Spring Boot Laboratories"
date: 03/08/2023
sidebar: false
---


:::
📘 Create a Spring Boot Project

Go to start.spring.io to create a new project with desired settings (Maven, Java, Spring Boot version, etc.).

Add required dependencies such as Spring Web.

Download the generated ZIP file and import it into IntelliJ IDEA.

Create web and REST controllers by creating new Java classes and defining the desired endpoint methods.

Run the application and test the web and REST controllers.

:::

## Project Initialization

Initializing project at the [Spring initializer tool](https://start.spring.io/){.external}

- Choosing settings  and adding dependencies for this project:

**TO-DO: Insert img**

## Importing project to Intellij Idea

**TO-DO: Insert img**

## Creating web controller

- Create a new Java Class.

In the previosuly created class add @Controller anotation to the class.

Create a Java method with the @RequestMapping anotation.
This controller will return an hmtl file.

**TO-DO: Insert img**

## Building a HTML page

Now it's time to build the html file that the controller will return.

On templates folder, create a new html file.

**TO-DO: Insert img**

## Creating REST controller

It's time to write the rest controller. It's quite similar to the creation of the web controller, but this time use the @Restcontroller and @GetMapping annotations.


**TO-DO: Insert img**

Now, the project tree looks like this:

**TO-DO: Insert img**

## Running out application

Now the project is to start running.

**TO-DO: Insert img**

and there are the responses 
 * web controller
 **TO-DO: Insert img**
 * rest controller
 **TO-DO: Insert img**

 Note the urls on the top. There are two different responses.

 **TO-DO: add github repo link**



